image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'cd "$project" && ./gradlew classes && cd ..; done' # runs during prebuild
  - command: 'cd "$project" && ./gradlew run'
  - command: 'gp await-port 8080 && gp preview $(gp url 8080)/docs'

ports:
  - port: 8080
    onOpen: ignore

github:
  prebuilds:
    master: true
